spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/mydb
    username: user
    password: pass1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: admin

rabbitmq:
  queue:
    kakao: kakao.message.queue
  exchange:
    kakao: kakao.message.exchange
  routing:
    kakao: kakao.message.routing

logging:
  level:
    org.springframework.security: DEBUG
